# Generated by Django 5.2 on 2025-04-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_location_speciality_user_is_doctor_user_is_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hospital_admin',
            field=models.BooleanField(default=False),
        ),
    ]
