# Generated by Django 5.2 on 2025-04-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_is_hospital_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.CharField(default='/static/images/doctor-avatar.png', max_length=200),
        ),
    ]
